[package]
name = "aoc_2018"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
lazy_static = "1.4.0"
chrono= "0.4.24"
arr_macro="0.2.1"
